FROM golang:1.14 as builder
RUN apt-get update && \
    apt-get install -y \
        gcc gcc-mingw-w64 gcc-multilib \
        git make \
        musl-dev liblzma-dev
RUN mkdir -p /go/src/github.com/michaelhobo/mender-artifact-1
WORKDIR /go/src/github.com/michaelhobo/mender-artifact-1
ADD ./ .
RUN make build-natives

FROM alpine:3.14.2
RUN apk add xz-dev
COPY --from=builder /go/src/github.com/michaelhobo/mender-artifact-1/mender-artifact* /go/bin/
ENTRYPOINT [ "/go/bin/mender-artifact-linux" ]
